#!/usr/bin/python
# -*- coding: UTF-8 -*- 
import sys
import json
import ast
line = sys.stdin.readline()
while line:
    object = ast.literal_eval(line)
    print(object)
    line = sys.stdin.readline()
