#!/bin/sh

echo "cd the script path "$(cd `dirname $0`; pwd)
if [ x$1 != x ]
then
	$(pwd)/getrss | $(pwd)/getvmessjson | $(pwd)/gentarjson > $1
else
	$(pwd)/getrss | $(pwd)/getvmessjson | $(pwd)/gentarjson > config.json
fi

